//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaWebBicicletas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CarroProducto
    {
        public int IdList { get; set; }
        public int IdCarro { get; set; }
        public int ProductoId { get; set; }
    
        public virtual Tbl_Carro Tbl_Carro { get; set; }
        public virtual Tbl_Producto Tbl_Producto { get; set; }
    }
}
